version: 2
jobs:
  build:
    branches:
      only:
        - master
        - stable
    machine: true
    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - run: npm run e2e

      # with credentials stored in the UI
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS reg.rallf.com:8443

      # build the application image
      - run: docker build . -t reg.rallf.com:8443/rec-admin:$CIRCLE_BRANCH

      # push the image
      - run: docker push reg.rallf.com:8443/rec-admin:$CIRCLE_BRANCH

      # use webhook to deploy
      - run: curl -X POST $DEPLOY_WEBHOOK
