name: Test, Build and Deploy [PROD]

on:
  release:
    types: [published]

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1
      - name: Login to Docker
        env:
          REGISTRY: reg.rallf.com:8443
          USER: ${{secrets.DOCKER_USERNAME}}
          PASS: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u ${USER} -p ${PASS} reg.rallf.com:8443

      - name: Build Docker image
        run: docker build . -t reg.rallf.com:8443/rec-admin:stable

      - name: Push Docker image
        run: docker push reg.rallf.com:8443/rec-admin:stable
        
      - name: Deploy
        uses: joelwmale/webhook-action@1.0.1
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_PROD }}
          data: "Hello from github actions!"
