name: Test, Build and Deploy [PROD]

on:
  push:
    branches:
      - stable

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Running test suite
        run: make test
  dev:
    # with credentials stored in the UI
    - name: Login to Docker
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS reg.rallf.com:8443

    # build the application image
    - name: Build Docker image
      run: docker build . -t reg.rallf.com:8443/rec-admin:stable

    # push the image
    - name: Push Docker image
      run: docker push reg.rallf.com:8443/rec-admin:stable

    # use webhook to deploy
    - name: Deploy webhook
      run: curl -X POST $DEPLOY_WEBHOOK
