name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v2

      - name: Copy env.dist.ts to dist.ts
        run: cp ./src/env.js.dist ./src/env.js

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@QbitArtifacts'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # - name: Install deps
      #   run: npm install

      - name: Test build
        run: npm run build:prod
