name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Install deps
        run: npm install

      - name: Running test suite
        run: npm test